package com.gemini.veintreebreaker;

import org.bukkit.Chunk;
import org.bukkit.NamespacedKey;
import org.bukkit.block.Block;
import org.bukkit.block.BlockState;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.world.StructureGrowEvent;
import org.bukkit.persistence.PersistentDataContainer;
import org.bukkit.persistence.PersistentDataType;

import java.util.Arrays;

public class PlacedBlockTracker implements Listener {

    private final VeinTreeBreaker plugin;
    private final NamespacedKey placedKey;

    public PlacedBlockTracker(VeinTreeBreaker plugin) {
        this.plugin = plugin;
        this.placedKey = new NamespacedKey(plugin, "player_placed");
    }

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onBlockPlace(BlockPlaceEvent event) {
        Block block = event.getBlockPlaced();
        // Only track materials the plugin actually interacts with (logs, ores, leaves)
        // Saplings, dirt, torches, etc. are ignored.
        if (plugin.isTrackedMaterial(block.getType())) {
            markBlockAsPlaced(block);
        }
    }

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onBlockBreak(BlockBreakEvent event) {
        unmarkBlockAsPlaced(event.getBlock());
    }

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onStructureGrow(StructureGrowEvent event) {
        // Clear all blocks generated by the tree/mushroom so they register as natural
        for (BlockState state : event.getBlocks()) {
            unmarkBlockAsPlaced(state.getBlock());
        }
    }

    public void markBlockAsPlaced(Block block) {
        Chunk chunk = block.getChunk();
        PersistentDataContainer pdc = chunk.getPersistentDataContainer();
        long blockKey = block.getBlockKey();
        long[] placedBlocks = pdc.get(placedKey, PersistentDataType.LONG_ARRAY);

        if (placedBlocks == null) {
            pdc.set(placedKey, PersistentDataType.LONG_ARRAY, new long[]{blockKey});
        } else {
            for (long key : placedBlocks) {
                if (key == blockKey) return; 
            }
            long[] newBlocks = Arrays.copyOf(placedBlocks, placedBlocks.length + 1);
            newBlocks[placedBlocks.length] = blockKey;
            pdc.set(placedKey, PersistentDataType.LONG_ARRAY, newBlocks);
        }
    }

    public void unmarkBlockAsPlaced(Block block) {
        Chunk chunk = block.getChunk();
        PersistentDataContainer pdc = chunk.getPersistentDataContainer();
        long[] placedBlocks = pdc.get(placedKey, PersistentDataType.LONG_ARRAY);

        if (placedBlocks != null) {
            long blockKey = block.getBlockKey();
            long[] newBlocks = Arrays.stream(placedBlocks).filter(k -> k != blockKey).toArray();
            
            if (newBlocks.length == 0) {
                pdc.remove(placedKey); 
            } else if (newBlocks.length != placedBlocks.length) {
                pdc.set(placedKey, PersistentDataType.LONG_ARRAY, newBlocks);
            }
        }
    }

    public boolean isPlayerPlaced(Block block) {
        Chunk chunk = block.getChunk();
        PersistentDataContainer pdc = chunk.getPersistentDataContainer();
        long[] placedBlocks = pdc.get(placedKey, PersistentDataType.LONG_ARRAY);

        if (placedBlocks != null) {
            long blockKey = block.getBlockKey();
            for (long key : placedBlocks) {
                if (key == blockKey) return true;
            }
        }
        return false;
    }
}